---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: AWS Infoblox config
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Set Provider Infoblox Data
      set_fact:
        provider:
          host: "{{ item.association.public_ip }}"
          username: "{{ username }}"
          password: "{{ password }}"
      loop: "{{ hostvars[groups['infoblox'][0]].network_interfaces }}"
      when: item.association is defined and item.association.public_ip is defined

    - name: Debug Provider Infoblox Data (Public IP, Username, Password) 
      debug:
        var: provider

    - name: Create an IPv4 Network {{ ipv4_network }}
      infoblox.nios_modules.nios_network:
        provider: "{{ provider }}"
        network_view: "{{ network_view }}"
        network: "{{ ipv4_network }}"
        comment: "Created Network {{ ipv4_network }}"
        state: present

    - name: Debug Next Available IPv4 Network {{ ipv4_network }}
      debug:
        msg: "Next Available IPv4 Network is {{ ipv4_network }}"

    - name: Get Next IPv4 Address from Network {{ ipv4_network }}
      ansible.builtin.set_fact:
        provider: "{{ provider }}"
        ipv4_address: "{{ lookup('infoblox.nios_modules.nios_next_ip', ipv4_network, network_view=network_view,
        num=1, exclude=ipv4_excluded_addresses, provider=provider)[0] }}"

    - name: Debug Next IPv4 Address {{ ipv4_address }}
      debug:
        msg: "Next IPv4 address from Network {{ ipv4_network }} is {{ ipv4_address }}"

    - name: Create IPv4 Fixed Address {{ ipv4_address }}
      infoblox.nios_modules.nios_fixed_address:
        provider: "{{ provider }}"
        network_view: "{{ network_view }}"
        network: "{{ ipv4_network }}"
        name: "{{ ipv4_hostname }}"
        ipaddr: "{{ ipv4_address }}"
        mac: "{{ mac_address }}"
        comment: "Created Fixed IPv4 Address {{ ipv4_network }}"
        state: present

    - name: Create DNS A Record for {{ ipv4_address }} -> {{ ipv4_hostname }}
      infoblox.nios_modules.nios_a_record:
        provider: "{{ provider }}"
        name: "{{ ipv4_hostname }}"
        ipv4addr: "{{ ipv4_address }}"
        view: "{{ dns_view }}"
        comment: "Created DNS A Record {{ ipv4_hostname }} -> {{ ipv4_address }}"
        state: present
