---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: AWS Infoblox config
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - debug
        var: hostvars[groups['infoblox'][0]]
    - name: Set Provider Infoblox Data
      set_fact:
        provider:
          host: "{{ hostvars[groups['infoblox'][0]].network_interfaces[1].association.public_ip }}"
          username: "{{ username }}"
          password: "{{ password }}"

    - name: Debug Provider Infoblox Data (Public IP, Username, Password) 
      debug:
        var: provider

    - name: Create a Network View {{ network_view }}
      infoblox.nios_modules.nios_network_view:
        provider: "{{ provider }}"
        name: "{{ network_view }}"
        state: present

    - name: Create an IPv4 Container Network {{ ipv4_container }}
      infoblox.nios_modules.nios_network:
        provider: "{{ provider }}"
        network_view: "{{ network_view }}"
        network: "{{ ipv4_container }}"
        comment: "Container Network {{ ipv4_container }}"
        container: true
        state: present

    - name: Get Next Available Network from Network Container {{ ipv4_container }}
      ansible.builtin.set_fact:
        ipv4_network: "{{ lookup('infoblox.nios_modules.nios_next_network', ipv4_container, ipv4_network_cidr,
          num=1, exclude=ipv4_excluded_networks, network_view=network_view, provider=provider)[0] }}"

    - name: Create an IPv4 Network {{ ipv4_network }}
      infoblox.nios_modules.nios_network:
        provider: "{{ provider }}"
        network_view: "{{ network_view }}"
        network: "{{ ipv4_network }}"
        comment: "Created Network {{ ipv4_network }}"
        state: present

    - name: Debug Next Available IPv4 Network {{ ipv4_network }}
      debug:
        msg: "Next Available IPv4 Network is {{ ipv4_network }}"

    - name: Get Next IPv4 Address from Network {{ ipv4_network }}
      ansible.builtin.set_fact:
        provider: "{{ provider }}"
        ipv4_address: "{{ lookup('infoblox.nios_modules.nios_next_ip', ipv4_network, network_view=network_view,
        num=1, exclude=ipv4_excluded_addresses, provider=provider)[0] }}"

    - name: Debug Next IPv4 Address {{ ipv4_address }}
      debug:
        msg: "Next IPv4 address from Network {{ ipv4_network }} is {{ ipv4_address }}"

    - name: Create IPv4 Fixed Address {{ ipv4_address }}
      infoblox.nios_modules.nios_fixed_address:
        provider: "{{ provider }}"
        network_view: "{{ network_view }}"
        network: "{{ ipv4_network }}"
        name: "{{ hostname }}"
        ipaddr: "{{ ipv4_address }}"
        mac: "{{ mac_address }}"
        comment: "Created Fixed IPv4 Address {{ ipv4_network }}"
        state: present
