---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: AWS Infoblox config
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - aws_infoblox_config
  
