---

- name: Create VPC {{ ec2_vpc_name }}
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    cidr_block: "{{ ec2_vpc_cidr }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      Name: "{{ ec2_vpc_name }}"
  register: vpc

- name: Create Subnet MGMT in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ ec2_subnet_cidr_mgmt }}"
    region: "{{ ec2_vpc_region }}"
    az: "{{ ec2_subnet_az }}"
    state: present
    tags:
      Name: "{{ ec2_subnet_name_mgmt }}"
  register: subnet_mgmt

- name: Create Subnet SRV in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ ec2_subnet_cidr_srv }}"
    region: "{{ ec2_vpc_region }}"
    az: "{{ ec2_subnet_az }}"
    state: present
    tags:
      Name: "{{ ec2_subnet_name_srv }}"
  register: subnet_srv

- name: Create Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      Name: "{{ ec2_igw_name }}"
  register: igw

- name: Create Route Table and IGW route
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      Name: "{{ ec2_rt_name }}"
    subnets:
      - "{{ subnet_mgmt.subnet.id }}"
      - "{{ subnet_srv.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- name: Create Security Group
  amazon.aws.ec2_security_group:
    name: "{{ ec2_sg_name }}"
    description: Allow all on ports
    state: present
    rules:
      - proto: tcp
        ports: "{{ ec2_sg_openports }}"
        cidr_ip: 0.0.0.0/0
        rule_desc: Allow all on ports
    region: "{{ ec2_vpc_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ ec2_sg_name }}"

- name: Get AMI by Name
  amazon.aws.ec2_ami_info:
    filters:
      #image-id: "{{ ec2_infoblox_image_id }}"
      name: "{{ ec2_infoblox_image_name }}"
    region: "{{ ec2_vpc_region }}"
  register: ami_infoblox_find

- name: Create ENI MGMT
  amazon.aws.ec2_eni:
    name: "{{ ec2_eni_name_mgmt }}"
    region: "{{ ec2_vpc_region }}"
    subnet_id: "{{ subnet_mgmt.subnet.id }}"
    security_groups: "{{ ec2_sg_name }}"
    delete_on_termination: true
    attached: false
    tags:
      Name: "{{ ec2_eni_name_mgmt }}"
    state: present
  register: eni_mgmt

- name: Create ENI SRV
  amazon.aws.ec2_eni:
    name: "{{ ec2_eni_name_srv }}"
    region: "{{ ec2_vpc_region }}"
    subnet_id: "{{ subnet_srv.subnet.id }}"
    security_groups: "{{ ec2_sg_name }}"
    delete_on_termination: true
    attached: false
    tags:
      Name: "{{ ec2_eni_name_srv }}"
    state: present
  register: eni_srv

- name: Create Infoblox instance
  amazon.aws.ec2_instance:
    image_id: "{{ ami_infoblox_find.images[-1].image_id | default('') }}"
    instance_type: "{{ ec2_infoblox_flavor_name }}"
    name: "{{ ec2_infoblox_instance_name }}"
    region: "{{ ec2_vpc_region }}"
    vpc_subnet_id: "{{ subnet_srv.subnet.id }}"
    key_name: "{{ ec2_infoblox_keypair_name }}"
    network_interfaces_ids:
      - id: "{{ eni_mgmt.interface.id }}"
        device_index: 0
      - id: "{{ eni_srv.interface.id }}"
        device_index: 1
    user_data: "{{ lookup('ansible.builtin.template', 'user_data.j2') }}"
    volumes: "{{ volumes }}"
    tags:
      Name: "{{ ec2_infoblox_instance_name }}"
    state: running
  register: ec2_infoblox_instance

- name: Allocate an Elastic IP to ENI SRV
  amazon.aws.ec2_eip:
    region: "{{ ec2_vpc_region }}"
    device_id: "{{ eni_srv.interface.id }}"
    in_vpc: true
    state: present
  register: eip_srv

- name: Print Infoblox instance details
  ansible.builtin.debug:
    msg: "Instance IP address {{ eip_srv.public_ip }}"

# Wait for boot ups
- name: Wait until Infoblox boots up
  wait_for:
    port: 443
    state: started
    timeout: 3600
    delay: 30
    host: "{{ eip_srv.public_ip }}"
