---

# - name: Refresh inventory
#   ansible.builtin.meta: refresh_inventory

- name: Get infoblox node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags.Name | regex_search("^infoblox-(.*)$")
  ignore_errors: true

- name: Add infoblox node to the infoblox group
  add_host:
    name: "{{ node_name }}"
    groups: "infoblox"
  when: infoblox is defined
