---

# - name: Refresh inventory
#   ansible.builtin.meta: refresh_inventory

- name: Get infoblox node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and  hostvars[item].tags.Name | regex_search("^infoblox-(.*)$")

- name: Add infoblox node to the infoblox group
  add_host:
    name: "{{ node_name }}"
    groups: "{{ group_name }}"
  when: node_name is defined
