# VPC
ec2_vpc_name: VPC_IB
ec2_vpc_region: us-east-1
ec2_vpc_cidr: 10.0.0.0/16
# Subnets
ec2_subnet_az: us-east-1a
ec2_subnet_name_mgmt: Subnet_IB_MGMT
ec2_subnet_cidr_mgmt: 10.0.0.0/24
ec2_subnet_name_srv: Subnet_IB_SRV
ec2_subnet_cidr_srv: 10.0.1.0/24
# ENIs
ec2_eni_name_srv: ENI_IB_SRV
ec2_eni_name_mgmt: ENI_IB_MGMT
# Elastic IP
ec2_eip_name_mgmt: EIP_IB_MGMT
# IGW
ec2_igw_name: IGW_IB
# Route Table
ec2_rt_name: RT_IB
# RHEL Open ports
ec2_sg_name: SG_IB
ec2_sg_openports:
  - 80
  - 443
  - 22
  - 514
  - 541
  - 542
  - 9433

# Infoblox
ec2_infoblox_instance_name: infoblox-1
ec2_infoblox_image_id: ami-0622a3d7a285429de
ec2_infoblox_image_name: Infoblox NIOS 9.0.5(BYOL)-3d6f2259-6756-484c-ac5e-f2d9330afe95
ec2_infoblox_flavor_name: m5.large #m6i.2xlarge 
ec2_infoblox_keypair_name: "KeyPair-Virginia"
ec2_infoblox_admin_pass: "{{ ansible_password }}"
volumes:
  - device_name: /dev/sda1
    ebs:
      volume_type: gp3
      volume_size: 500
      delete_on_termination: true
  - device_name: /dev/sdb
    ebs:
      volume_type: gp3
      volume_size: 500
      delete_on_termination: true

