---

- name: Set Provider Infoblox Data
  set_fact:
    provider:
      host: "{{ hostvars[groups['infoblox'][0]].network_interfaces[1].association.public_ip }}"
      username: "{{ username }}"
      password: "{{ password }}"

- name: Debug Provider Infoblox Data (Public IP, Username, Password) 
  debug:
    var: provider

- name: Get Existing Networks
  ansible.builtin.set_fact:
    networks: "{{ lookup('infoblox.nios_modules.nios_lookup', 'network', provider=provider) }}"

- name: For the single network particular case (it returns a dict)
  set fact:
    networks: "{{ networks | list }}"
  when: networks | type_debug != "list"

- name: Debug Existing Networks
  debug:
    msg: "Network: {{ item.network }}"
  loop: "{{ networks }}"

- name: Create an IPv4 Network {{ ipv4_network }}
  infoblox.nios_modules.nios_network:
    provider: "{{ provider }}"
    network: "{{ ipv4_network }}"
    comment: "Network {{ ipv4_network }}"
    state: present

- name: Get Next IPv4 Address from Network {{ ipv4_network }}
  ansible.builtin.set_fact:
    provider: "{{ provider }}"
    ip_address: "{{ lookup('infoblox.nios_modules.nios_next_ip', ipv4_network, provider=provider) }}"

- name: Debug Next IPv4 Address {{ ip_address }}
  debug:
    msg: "Next IPv4 address from Network {{ ipv4_network }} is {{ ip_address }}"

# - name: Delete an IPv4 Network {{ ipv4_network }}
#   infoblox.nios_modules.nios_network:
#     provider: "{{ provider }}"
#     network: "{{ ipv4_network }}"
#     comment: "Network {{ ipv4_network }}"
#     state: absent