---

- name: Debug vars
  debug:
    msg: "{{ inventory_hostname }}"

- name: Debug vars
  debug:
    msg: "{{ ansible_host }}"

- name: Debug vars
  debug:
    var: hostvars[groups['infoblox'][0]]
#        ip: "{{ hostvars[groups['fortigate'][0]].private_ip_address }}"

- name: Debug vars
  debug:
    msg: "{{ groups['infoblox'].ansible_host }}"

- name: Get existing IPv4 Networks
  ansible.builtin.set_fact:
    networks: "{{ lookup('infoblox.nios_modules.nios_lookup', 'network', provider=provider) }}"

- name: Debug existing networks
  debug:
    var: networks

- name: Create an IPv4 Network
  infoblox.nios_modules.nios_network:
    provider: "{{ provider }}"
    network: "{{ ipv4_network }}"
    comment: "Network {{ ipv4_network }}"
    state: present

- name: Get Next IPv4 Address from Network {{ ip_network }}
  ansible.builtin.set_fact:
    provider: "{{ provider }}"
    ip_address: "{{ lookup('infoblox.nios_modules.nios_next_ip', 'ip_network', provider=provider) }}"

- name: Get Next IPv6 Address
  debug:
    msg: "Next IP address from Network {{ ip_network }} is {{ ip_address }}"

- name: Delete an IPv4 Network
  infoblox.nios_modules.nios_network:
    provider: "{{ provider }}"
    network: "{{ ipv4_network }}"
    comment: "Network {{ ipv4_network }}"
    state: absent