---

- name: Query VPCs
  amazon.aws.ec2_vpc_net_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ ec2_vpc_name }}"
  register: vpc

- name: Query Subnet SRV
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ ec2_subnet_name_srv }}"
  register: subnet_srv

- name: Query ENI MGMT
  amazon.aws.ec2_eni_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ ec2_eni_name_mgmt }}"
  register: eni_mgmt

- debug: 
    var: eni_mgmt

- name: Query Route Tables
  amazon.aws.ec2_vpc_route_table_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ ec2_rt_name }}"
  register: rtb

- name: Dellocate a Elastic IP in ENI MGMT
  amazon.aws.ec2_eip:
    region: "{{ ec2_vpc_region }}"
    device_id: "{{ eni_mgmt.network_interface.network_interface_id }}"
    in_vpc: true
    state: absent
  register: eip_mgmt

- name: Terminate Infoblox instance
  amazon.aws.ec2_instance:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:Name": "{{ ec2_infoblox_instance_name }}"
    state: absent

- name: Delete Security Group
  amazon.aws.ec2_group:
    name: "{{ ec2_sg_name }}"
    region: "{{ ec2_vpc_region }}"
    state: absent

- name: Delete ENI MGMT
  amazon.aws.ec2_eni:
    name: "{{ ec2_eni_name_mgmt }}"
    subnet_id: "{{ subnet_mgmt.subnets[0].subnet_id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: subnet_mgmt.subnets | length > 0

- name: Delete Subnet SRV in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    cidr: "{{ subnet_srv.subnets[0].cidr_block }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: vpc.vpcs | length > 0 and subnet_srv.subnets | length > 0

- name: Delete Subnet MGMT in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    cidr: "{{ subnet_mgmt.subnets[0].cidr_block }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: vpc.vpcs | length > 0 and subnet_mgmt.subnets | length > 0

- name: Delete Route Table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ ec2_vpc_region }}"
    route_table_id: "{{ rtb.route_tables[0].id }}"
    lookup: id
    state: absent
  when: vpc.vpcs | length > 0 and rtb.route_tables | length > 0

- name: Delete Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: vpc.vpcs | length > 0

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    region: "{{ ec2_vpc_region }}"
    cidr_block: "{{ vpc.vpcs[0].cidr_block }}"
    state: absent
  when: vpc.vpcs | length > 0

